version: '3'
services:
    web:
        # image: nginx
        build: .docker/nginx
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html/public
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - db
        networks:
            - app

    php:
        build: .docker
        restart: always
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - .:/var/www/html/public
        networks:
            - app
        working_dir: /var/www/html/public

    composer:
        image: composer
        volumes:
            - .:/app
        command: install
        networks:
            - app

    db:
        image: mysql:8.0
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
        networks:
            - app

networks:
    app:
        driver: bridge
